services:
  - type: web
    name: bridge-simulator
    runtime: docker
    envVars:
      - key: PYTHONPATH
        value: ".:./redeal"
    # This tells Render specifically to handle submodules correctly
    repo: https://github.com/SiegEPS/BridgeSimulator
    branch: main